version: '3.7'

services:
  front:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: front
    stdin_open: true
    environment:
      # Reach backend server
      - SYLIUS_BASE_URL=http://nginx:80
    volumes:
       - ./:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules

# Use network managed by the backend
networks: 
  default: 
    name: sylius-vuestorefront
    external: true