import { AgnosticMediaGalleryItem, AgnosticAttribute, AgnosticPrice, ProductGetters } from '@vue-storefront/core';
import { Product } from '@vue-storefront/sylius-api/src/types';
declare type ProductVariantFilters = any;
export declare const getProductName: (product: Product) => string;
export declare const getProductSlug: (product: Product) => string;
export declare const getProductPrice: (product: Product) => AgnosticPrice;
export declare const getProductGallery: (product: Product) => AgnosticMediaGalleryItem[];
export declare const getProductCoverImage: (product: Product) => string;
export declare const getProductFiltered: (products: Product[], filters?: ProductVariantFilters | any) => Product[];
export declare const getProductAttributes: (products: Product[] | Product, filterByAttributeName?: string[]) => Record<string, AgnosticAttribute | string>;
export declare const getProductOptions: (product: Product) => any;
export declare const getProductDescription: (product: Product) => any;
export declare const getProductCategoryIds: (product: Product) => string[];
export declare const getProductId: (product: Product) => string;
export declare const getFormattedPrice: (price: number) => string;
export declare const getProductTotalReviews: (product: Product) => number;
export declare const getProductAverageRating: (product: Product) => number;
export declare const productGetters: ProductGetters<Product, ProductVariantFilters>;
export {};
